-- sql/supabase-policies.sql
-- Example schema + RLS policies for a transactions table.
-- Run in Supabase SQL editor (adjust table/column names as needed).

-- Table
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid,
  symbol text not null,
  qty numeric not null,
  price numeric not null,
  date date not null,
  note text,
  inserted_at timestamptz default now()
);

-- Enable RLS
alter table public.transactions enable row level security;

-- Policy: allow authenticated users to insert rows for themselves
create policy "Insert own transactions" on public.transactions
  for insert using (auth.role() = 'authenticated')
  with check (auth.uid() = user_id);

-- Policy: allow authenticated users to select their own rows
create policy "Select own transactions" on public.transactions
  for select using (auth.uid() = user_id);

-- Policy: allow authenticated users to update/delete only their rows
create policy "Modify own transactions" on public.transactions
  for update, delete using (auth.uid() = user_id);

-- Optional: create a read-only view for public visitors (if you want public portfolio view)
-- Example: public.transactions_public_view (select only aggregated or sanitized data)
create or replace view public.transactions_public_view as
select id, symbol, qty, date, price from public.transactions where false; -- change to allow selective visibility as needed

-- NOTE:
-- If you want visitors to view the portfolio without auth, create a VIEW (with aggregated data)
-- and set a policy to allow public select on that view only. Keep original table write access locked down.